stages:
  - deploy

build-and-deploy-docker:
  stage: deploy
  only:
    - develop
  image: docker:stable
  services:
    - name: docker:dind
      alias: theDockerHost
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://theDockerHost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
